dist: bionic
language: python
sudo: false
cache:
  pip: true
  directories:
  - downloads
  - eggs
python:
  - "2.7"
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION="4.3" PART="test"
    - python: "2.7"
      env: PLONE_VERSION="5.1" PART="test"
    - python: "2.7"
      env: PLONE_VERSION="5.2" PART="test"
    - python: "3.7"
      env: PLONE_VERSION="5.2" PART="test"
    - python: "3.7"
      env: PLONE_VERSION="5.2" PART="code-analysis"
  sudo: true
  fast_finish: true
before_install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - sed -ie "s#5.2-latest#$PLONE_VERSION-latest#" buildout.cfg
  - bin/buildout -N code-analysis:return-status-codes=True annotate
install:
  - bin/buildout -N code-analysis:return-status-codes=True install $PART
script:
  - bin/$PART
